SAMPLING_RATE: 16000

INFLUXDB:
  URL: "http://localhost:8086"
  TOKEN: "aaM5fz5n-KDzZl0iNZ_Dc9k65sdKi9-VyI_-wHAcFHWTwL58StOfrb_W7xu-n2GCZbYJdhihlRCUya2n9jU8wg=="
  ORG: "UNF"
  BUCKET: "Audio Logger"  

NAC:
  MODEL_PATH: "/home/ste/Code/audiologger/DBClient/model/quant_decoder_components.ckpt"

MQTT:
  BROKER_ADDRESS: "localhost"